// 'use client';
import Head from 'next/head';

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  Container,
  Typography,
  Box,
} from '@mui/material';
import { useEffect, useState } from 'react';

// import { app } from '../../firebase';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '../../firebase';
import Header from '@/components/header';
import BreadCrumb from '@/components/breadCrumb';
import AddedCheckin from '@/components/addedCheckin';
// import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div
          style={{
            width: '78%',
            margin: ' 0 auto',
            height: '64px',
            borderRadius: '50px',
            // paddingBottom: '20px',
          }}
          sx={{
            boxShadow: '14px 17px 40px 0px rgba(112, 144, 176, 0.08)',
            // Custom shadow converted
          }}
        >
          <Header />
          <BreadCrumb />
          <AddedCheckin />
        </div>
      </div>
    </>
  );
}
